/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
//import javax.swing.ImageIcon;
import AuraMain.*;

import javax.swing.*;

/**
 *
 * @author Dan Bennett-Jeffreys
 */
public class PrimaryButtonPanel extends JPanel {
    
    /**
     * Creates new form PrimaryButtonPanel
     */
    public PrimaryButtonPanel() {
        initComponents();
        jAddFile.addActionListener(new AddFileListener());
        jAddFldr.addActionListener(new AddFolderListener()); // Please fix so it isn't RemoveFolderListener -o
        jClrAll.addActionListener(new ClearAllListener());
        jRmvFile.addActionListener(new RemoveFileListener());
        jStart.addActionListener(new StartListener());
        jCustomPanel.addActionListener(new CustomListener());
    }

    public void setFormat(String newFormat){
        jFormat.setSelectedItem(newFormat);
    }
    
    /**
     * ActionListener for Add File Button
     */
    public class AddFileListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            try { Uploader.openFileBrowser("FILE"); } catch(Exception ee) {}
        }
    }
    
    /**
     * ActionListener for Remove File Button
     */
    public class RemoveFileListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            UI.removeSelectedFiles();
        }
    }
    
    /**
     * ActionListener for Wipe All Button
     */
    public class ClearAllListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            UI.wipeAllFiles();
        }
    }
    
    /**
     * ActionListener for Add Folder Button
     */
    public class AddFolderListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            System.out.println("AddFolderListener");
            try { Uploader.openFileBrowser("FOLDER"); } catch(Exception ee) { System.out.println(ee);}
        }
    }
    
    /**
     * ActionListener for Start Button
     */
    public class StartListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            UI.doConvert(UI.getFilesEnqueued());
        }
    }
    
    /**
     * ActionListener for Custom Metadata Button
     */
    public class CustomListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            if(UI.getPanelIndices().length == 0){
                UI.sendNotification("err","You must select a file to modify its data!");
                return;
            }
            CustomMetaPnl cmP = new CustomMetaPnl();

        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAddFile = new javax.swing.JButton();
        jRmvFile = new javax.swing.JButton();
        jAddFldr = new javax.swing.JButton();
        jClrAll = new javax.swing.JButton();
        jCustomPanel = new javax.swing.JButton();
        jFormat = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jStart = new javax.swing.JButton();

        setBackground(new java.awt.Color(236, 220, 118));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(300, 200));

        jAddFile.setBackground(new java.awt.Color(204, 255, 204));
        jAddFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addfile.png"))); // NOI18N
        jAddFile.setToolTipText("Add File");

        jRmvFile.setBackground(new java.awt.Color(255, 204, 204));
        jRmvFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/removefile.png"))); // NOI18N
        jRmvFile.setToolTipText("Remove File");

        jAddFldr.setBackground(new java.awt.Color(204, 255, 204));
        jAddFldr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/folderadd.png"))); // NOI18N
        jAddFldr.setToolTipText("Add Folder");

        jClrAll.setBackground(new java.awt.Color(255, 204, 204));
        jClrAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/deleteall.png"))); // NOI18N
        jClrAll.setToolTipText("Clear File List");

        jCustomPanel.setText("Custom Metadata");
        jCustomPanel.setToolTipText("Custom Meta");
        jCustomPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCustomPanelActionPerformed(evt);
            }
        });

        jFormat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<keep>", "mp3", "ogg", "flac", "wav", "aac" }));
        jFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormatActionPerformed(evt);
            }
        });

        jLabel1.setText("Format");

        jStart.setBackground(new java.awt.Color(102, 204, 255));
        jStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/start.png"))); // NOI18N
        jStart.setToolTipText("Convert Files");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAddFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRmvFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAddFldr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jClrAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jStart))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCustomPanel)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAddFile)
                    .addComponent(jRmvFile)
                    .addComponent(jAddFldr)
                    .addComponent(jClrAll)
                    .addComponent(jStart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCustomPanel))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jFormatActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jFormatActionPerformed
        UI.formatChanged((String)jFormat.getSelectedItem());
    }//GEN-LAST:event_jFormatActionPerformed

    private void jCustomPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCustomPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCustomPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddFile;
    private javax.swing.JButton jAddFldr;
    private javax.swing.JButton jClrAll;
    private javax.swing.JButton jCustomPanel;
    private javax.swing.JComboBox<String> jFormat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jRmvFile;
    private javax.swing.JButton jStart;
    // End of variables declaration//GEN-END:variables
}
