/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
//import javax.swing.ImageIcon;
import EchoMain.*;

/**
 *
 * @author Dan Bennett-Jeffreys
 */
public class PrimaryButtonPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form PrimaryButtonPanel
     */
    public PrimaryButtonPanel() {
        initComponents();
        jAddFile.addActionListener(new AddFileListener());
        jAddFldr.addActionListener(new AddFolderListener()); // Please fix so it isn't RemoveFolderListener -o
        jClrAll.addActionListener(new ClearAllListener());
        jRmvFile.addActionListener(new RemoveFileListener());
        jStart.addActionListener(new StartListener());
    }

    /**
     * ActionListener for Add File Button
     */
    public class AddFileListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            try { Uploader.openFileBrowser("FILE"); } catch(Exception ee) {}
        }
    }
    
    /**
     * ActionListener for Remove File Button
     */
    public class RemoveFileListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            UI.removeSelectedFiles();
        }
    }
    
    /**
     * ActionListener for Wipe All Button
     */
    public class ClearAllListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            UI.wipeAllFiles();
        }
    }
    
    /**
     * ActionListener for Add Folder Button
     */
    public class AddFolderListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            System.out.println("AddFolderListener");
            try { Uploader.openFileBrowser("FOLDER"); } catch(Exception ee) { System.out.println(ee);}
        }
    }
    
    /**
     * ActionListener for Start Button
     */
    public class StartListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            UI.doConvert(UI.getFilesEnqueued());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAddFile = new javax.swing.JButton();
        jRmvFile = new javax.swing.JButton();
        jAddFldr = new javax.swing.JButton();
        jRmvFldr = new javax.swing.JButton();
        jClrAll = new javax.swing.JButton();
        jStart = new javax.swing.JButton();
        jStop = new javax.swing.JButton();
        jFormat = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jAddFile.setText("Add File");

        jRmvFile.setText("Remove File");

        jAddFldr.setText("Add Folder");

        jRmvFldr.setText("Remove Folder");

        jClrAll.setText("Clear File/Folder List");

        jStart.setText("Start");

        jStop.setText("Stop");

        jFormat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mp3", "m4a", "flac", "wav", "wma", "aac", "ogg" }));
        jFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormatActionPerformed(evt);
            }
        });

        jLabel1.setText("Format");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jAddFldr)
                                .addGap(18, 18, 18)
                                .addComponent(jRmvFldr))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jAddFile)
                                .addGap(18, 18, 18)
                                .addComponent(jRmvFile))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jStart)
                                .addGap(18, 18, 18)
                                .addComponent(jStop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(25, 25, 25))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jClrAll)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAddFile)
                            .addComponent(jRmvFile))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAddFldr)
                            .addComponent(jRmvFldr))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jStart)
                            .addComponent(jStop))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(jFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addComponent(jClrAll)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Format");
    }// </editor-fold>//GEN-END:initComponents

    private void jFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormatActionPerformed
        UI.formatChanged((String)jFormat.getSelectedItem());
    }//GEN-LAST:event_jFormatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddFile;
    private javax.swing.JButton jAddFldr;
    private javax.swing.JButton jClrAll;
    private javax.swing.JComboBox<String> jFormat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jRmvFile;
    private javax.swing.JButton jRmvFldr;
    private javax.swing.JButton jStart;
    private javax.swing.JButton jStop;
    // End of variables declaration//GEN-END:variables
}
