/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import EchoMain.*;

/**
 *
 * @author Dan Bennett-Jeffreys
 */
public class PrimaryButtonPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form PrimaryButtonPanel
     */
    public PrimaryButtonPanel() {
        initComponents();
        jAddFile.addActionListener(new AddFileListener());
        jAddFldr.addActionListener(new AddFolderListener()); // Please fix so it isn't RemoveFolderListener -o
        jClrAll.addActionListener(new ClearAllListener());
        jRmvFile.addActionListener(new RemoveFileListener());
        jRmvFldr.addActionListener(new RemoveFolderListener());
        jStart.addActionListener(new StartListener());
        jStop.addActionListener(new StopListener());
    }

    public class AddFileListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            try { Uploader.openFileBrowser("FILE"); } catch(Exception ee) {}
        }
    }
    
    public class RemoveFileListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            UI.removeSelectedFiles();
        }
    }
    
    public class ClearAllListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            UI.wipeAllFiles();
        }
    }
    
    public class AddFolderListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            System.out.println("AddFolderListener");
            try { Uploader.openFileBrowser("FOLDER"); } catch(Exception ee) { System.out.println(ee);}
        }
    }
    
    public class RemoveFolderListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            
        }
    }
    
    public class StartListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            UI.doConvert(UI.getFilesEnqueued());
        }
    }
    
    public class StopListener implements ActionListener{ //We may not need this, depends... -o
        @Override
        public void actionPerformed(ActionEvent e){
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAddFile = new javax.swing.JButton();
        jRmvFile = new javax.swing.JButton();
        jAddFldr = new javax.swing.JButton();
        jRmvFldr = new javax.swing.JButton();
        jClrAll = new javax.swing.JButton();
        jStart = new javax.swing.JButton();
        jStop = new javax.swing.JButton();

        jAddFile.setText("Add File");

        jRmvFile.setText("Remove File");

        jAddFldr.setText("Add Folder");

        jRmvFldr.setText("Remove Folder");

        jClrAll.setText("Clear File/Folder List");

        jStart.setText("Start");

        jStop.setText("Stop");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jStart)
                                .addGap(18, 18, 18)
                                .addComponent(jStop))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jAddFldr)
                                .addGap(18, 18, 18)
                                .addComponent(jRmvFldr))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jAddFile)
                                .addGap(18, 18, 18)
                                .addComponent(jRmvFile))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jClrAll)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddFile)
                    .addComponent(jRmvFile))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddFldr)
                    .addComponent(jRmvFldr))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStart)
                    .addComponent(jStop))
                .addGap(18, 18, 18)
                .addComponent(jClrAll)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddFile;
    private javax.swing.JButton jAddFldr;
    private javax.swing.JButton jClrAll;
    private javax.swing.JButton jRmvFile;
    private javax.swing.JButton jRmvFldr;
    private javax.swing.JButton jStart;
    private javax.swing.JButton jStop;
    // End of variables declaration//GEN-END:variables
}
